table Dim_Vendedor
	lineageTag: 44bd305b-33ec-4162-852a-631ad35e021d

	column ID_Vendedor
		dataType: int64
		formatString: 0
		lineageTag: e40f8175-8f9d-4530-a538-98440e54a4b8
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: 004e5c8c-3414-4afe-b684-2217f1131953
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column fecha_nacimiento
		dataType: dateTime
		formatString: General Date
		lineageTag: f541cde0-b806-4871-8b44-450f85748811
		summarizeBy: none
		sourceColumn: fecha_nacimiento

		variation Variación
			isDefault
			relationship: ad6a84c3-303c-41f5-a770-7c4a09f6c3e3
			defaultHierarchy: LocalDateTable_45544661-c266-4f7e-862a-a71cd65722de.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Foto
		dataType: string
		lineageTag: 5b5ca616-caff-4c86-8c14-6e4b87c26648
		summarizeBy: none
		sourceColumn: Foto

		annotation SummarizationSetBy = Automatic

	partition Dim_Vendedor = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\jluis\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Vendedor_Table = Origen{[Item="Dim_Vendedor",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Vendedor_Table,{{"ID_Vendedor", Int64.Type}, {"Vendedor", type text}, {"fecha_nacimiento", type datetime}, {"Foto", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

