table Medidas
	lineageTag: fdcb6b4f-0c00-4577-8b6b-9af72dd28469

	measure VentasPorCanal = COUNTROWS(Fact_Ventas)
		formatString: 0
		lineageTag: c57ffedc-9c40-4c8e-9c44-d4f39545a89d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Total Sales with IGV' = SUMX(Fact_Ventas, Fact_Ventas[Precio Venta sin IGV] + Fact_Ventas[IGV])
		lineageTag: d871cfee-be1e-43b0-ae67-be68a5155aa1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Columna1
		dataType: string
		lineageTag: 8bc0d2fa-e0b0-49e5-8fd8-f6660e1e0501
		summarizeBy: none
		sourceColumn: Columna1

		annotation SummarizationSetBy = Automatic

	partition Medidas = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

